refactor: download process to use worker pool to fetch page concurrently
CEDT-Chula/download-learn-eltngl-ebook pull request #1
Opened 2024-08-24 08:21 UTC by punchanabu

- for me it takes forever to download an entire book
## Description
- Introduced a worker pool pattern to fetch pages concurrently
- improved logging a little bit

## Before
- it takes like 10 min to scrape now and I dont see any progress
<img width="511" alt="Screenshot 2567-08-24 at 15 19 31" src="https://github.com/user-attachments/assets/3df18278-6a6a-4551-91b0-9e9913f0ee7d">

## After 
- i downloaded the entire book in 3.54 mins
<img width="436" alt="Screenshot 2567-08-24 at 15 11 11" src="https://github.com/user-attachments/assets/a42cc612-a5e4-4ddd-859b-d4a856163b67">

2024-08-24 08:22 UTC, apiphoomchu commented
@NewBieCoderXD

2024-08-24 09:11 UTC, NewBieCoderXD commented
Nice work!
Didn't think there is a performance issue (it only takes 11 seconds for my english ebook on my windows machine)
However, I've tested on windows, logging seems like a mess, is this intended?
![image](https://github.com/user-attachments/assets/8ac6dc83-7b0b-4f37-b2dd-2e0e6878d1ce)

It works fine on Ubuntu though, bring down run time from 45 seconds to 36 seconds, good job!

btw, what ebook were you downloading? 3 minutes is still quite shocking

(reviewing is still in progress)

2024-08-24 09:13 UTC, NewBieCoderXD commented on main.go
> +	numWorkers := 10
is there a reason you don't use runtime.NumCPU() number of workers?

2024-08-25 13:03 UTC, NewBieCoderXD requested changes

2024-08-25 13:03 UTC, NewBieCoderXD commented on main.go
> +		pdfWriter.AddPage(pageResult.Page)
Can you use arrays instead of channels? (both jobs, results, errors)
I think it might be more optimal
and if done right, it is completely safe without locking, because we can isolate array indices
that way we don't even have to sort
[See also](https://groups.google.com/g/golang-nuts/c/trmXxcyJxVo?pli=1)

But if you're worrying about non-contiguous memory, let me know

2025-01-09 07:10 UTC, merged

2025-01-09 07:10 UTC, NewBieCoderXD commented
I'll fix it myself.
Thanks for the PR!